### ISSUE TITLE
Distinguish between reproducible public data and not-reproducible data

### ISSUE THREAD

**Issue by tjayrush** [OpenDataforWeb3/Resources#3]
When dealing with immutable, open, shared data, I think there are two types of data: reproducible and not-reproducible.

Reproducible data is either:
- directly under consensus in the block data, or
- data directly derivable from block data through a deterministic algorithm.

Not-reproducible is !(reproducible) -- in other words, everything else.

Some examples of the former are - block and transaction hashes, events appearing in a given transaction, a list of addresses appearing in a given transaction including all traces, logs, receipts, etc (or the same in a block), a petname derived deterministically from an address, a four-byte encoding derived from a function signature, etc.

An example of not-reproducible data is the names associated with an address (even names queried from a smart contract, if the name can be changed over time). Another example is the list of transactions in the mem-pool prior to being enshrined in a block.

Token transfers (excluding mints) are reproducible and clearly defined because of the existence of the ERC20 standard. Things such as loaning, borrowing, or staking are not reproducible because there is no way to clearly and unequivocally identify such things due to the lack of a standard.

I think it would be beneficial to keep these two things separate in our minds as we discuss Open Data. If something is reproducible from purely on-chain data with a deterministic algorithm, then it's already wide open. In fact, I think it's so wide open, it cannot be made otherwise.

For those things that are not already open, we need to be much more careful because this is where the difficulty will arise. After all, who's to say that address 0x1234 should be called "Jim's contract" vs. "John's contract." There's literally no way to know the correct answer.

**Comment by epowell101** [comment]
Excellent.  To further clarify and educate - is it the case that the !(reproducible) would fit in the readme here as a part of a new section that we might add for additional feedback titled "Open Data" along these lines (i.e. please review @tjayrush )
--------- suggested section:  

OpenData:

**- On-chain and reproducible:** for example, ERC-20 transactions and other transactions that conform to a known standard and are recorded on-chain
     - Curation:  This data is publicly available and is in some ways the foundation of web3.  We do not see a need to assist in the collection and curation of this data.
     - Indexing and APIs:  While on-chain reproducible data is widely available, there remain use cases for the indexing of the data as well as even higher-level transformations and analysis.  
      
- **On-chain and *not* reproducible:** for example, transactions by lending, staking, borrowing, and other smart contracts that do not conform to a known standard; other examples include transactions in the mem-pool prior to being enshrined in a block and the names associated with an address.  These transactions may require consideration before usage to determine whether they are accurate.
     - Curation:  While this data is publicly available, it can profit from curation that seeks to determine whether the transactions that are recorded are comprehensive and otherwise accurate.
     - Indexing and APIs:  Indexes and APIs and higher-level transformation and analysis are valuable.
     
- **Off-chain data:** Off-chain data refers to all data that is not recorded on-chain. This data can be important for web3 purposes. It is a fairly unbounded domain. For the purposes of this community, we focus on that data that is either stored in decentralized infrastructure such as IPFS or that is otherwise emitted in the course of web3 operations, such as public funding grants rounds, airdrop white lists, and similar.

**Comment by tjayrush** [comment]
> This data is publicly available and is in some ways the foundation of web3. We do not see a need to assist in the collection and curation of this data.

I'm not sure this is completely true. For example, the ERC20 token standard makes minting a SHOULD, but it does not make it a MUST, which means that in some cases (perhaps not many, and definitely a lot less today than earlier on the chain) the initial distribution of the token can not be re-constituted from events only.

Because it is the foundation of web 3 (token transfers are), I think at the very least there needs to be discussion about when, why, and how some ERC20 token asset change hands, but do not have events generated.

**Comment by sarob** [comment]
Let's publish this as a doc on the website and close this issue.
